# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THT4oKE2ibmmWLRGzRusUnto6quc09XF
"""

import pandas as pd
import numpy as np
from pandas import Series



genres_df = pd.read_csv('genres.csv', sep=',',encoding = "ISO-8859-1")
genres_df = genres_df.dropna(how='any')
subset_df = pd.concat([Series(row['imdb_id'], row['genre'].split(', '))
                    for _, row in genres_df.iterrows()]).reset_index()
subset_df.columns = ['genres','movie_ID']
pd.crosstab(subset_df.genres, subset_df.movie_ID)





































































































subset_df.iloc[0:10]











